api_platform:
    title: Hello API Platform
    version: 1.0.0
    exception_to_status:
        App\Exception\UnprocessableEntityException: 422

    show_webby: false

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_partial: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_client_partial: true
        pagination_maximum_items_per_page: 100

    eager_loading:
        force_eager: false

    formats:
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/ValueObject'
        - '%kernel.project_dir%/src/Controller'

    eager_loading:
        enabled: false
