name: Test Back-End

on:
  workflow_call:
  pull_request:
    types:
      - opened
  push:
    branches_ignore:
      - main # not in main as test will be workflow_call by deploy
    paths:
      - 'api/**'
      - '.github/workflows/back-test.yml'

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build

      - name: Add phpunit
        run: composer require phpunit

      - name: Run tests
        run: bin/phpunit tests/